### ISSUE TITLE
php artisan db-exporter:seed does not work

### ISSUE THREAD

**Issue by ketanhtrentiya** [vi-kon/laravel-db-exporter#2]
hey there....
i found the below error in terminal
when i input....
$ php artisan db-exporter:seed

---

[InvalidArgumentException]  
  Command "db-exporter:seed" is not defined.  
  Did you mean one of these?  
      db:seed  
      make:seeder  
      db-exporter:migrate 

---

please give me suggestion for overcome this problem,
i must have to use this package for my current project

Thanks in advance

**Comment by vincekovacs** [comment]
Hi, currently this feature is available only in `develop` branch.

You have to change in `composer.json` following line `"vi-kon/laravel-db-exporter": "~1.*"` to `"vi-kon/laravel-db-exporter": "dev-develop"`

After it you can use `db-exporter:seed` command.

If any error occurs please let me know.

**Comment by ketanhtrentiya** [comment]
hi,
Its work from terminal,
Thanks

But please, can you tell me how to do it into Laravel 5.1 Controller instead of terminal
Sorry,  i should ask for controller in my previous comment.
i.e. into Laravel 5.1 Controller
'php artisan db-exporter:seed'

at the moment, i am doing it like below in my laravel controller,
but it neither give error nor work. 

---

Artisan::call('db-exporter:seed');

---

Thanks

**Comment by vincekovacs** [comment]
Hi,
I will see what can I do. I did not tested in controller.

**Edit:**
There was error in config file. The paths were changed to absolute. I quick tested inside a route and controller and it work.
